spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /yqcoding
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    # 开启到达 Broker 确认 开启
    publisher-confirms: true
    # 开启 return consumer 消费完成确认
    publisher-returns: true
    template:
      mandatory: true
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yqcoding?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      # 连接池中等待连接最长时间
      connection-timeout: 30000
      # 连接闲置最长时间
      idle-timeout: 600000
      # 连接池中连接的生命周期时间
      max-lifetime: 900000
      # 连接的其他配置参数 mysql 推荐经典参数
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false