server:
  port: 1700
  servlet:
    context-path: /yqcoding
spring:
  application:
    name: yqcoding
  profiles:
    active: dev
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:com/anserx/yqcoding/**/*.xml
# 队列定义
yqcoding.mq:
  definitions:
    - com.anserx.yqcoding.mq.enums.QueueDefinitionEnum
kaptchaCode:
  timeout: 5
logging:
  level:
    com.anserx.yqcoding: debug