server:
  port: 1700
  servlet:
    context-path: /yqcoding
spring:
  application:
    name: yqcoding
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
    encoding:
      charset: UTF-8
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:com/anserx/yqcoding/**/*.xml
# 队列定义
yqcoding.mq:
  definitions:
    - com.anserx.yqcoding.mq.enums.QueueDefinition1Enum
    - com.anserx.yqcoding.mq.enums.QueueDefinitionEnum
